export const allTopics = [
    "Cloud Computing",
    "Computer Networks",
    "Data Structures & Algorithms",
    "CS Fundamentals",
    "C",
    "C++",
    "Java",
    "Python",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Express",
    "MongoDB",
    "SQL / Databases",
    "System Design",
    "HTML & CSS",
    "API Design",
];
